# Site Settings
name: Peter Marsh
title: "Hi, I'm Peter :) Welcome to my website"
description: "A UCLA Engineering Grad with a BS in Biomedical Engineering
and an emphasis in Computer Science. Click learn more about me!"
tags:
  - about me
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: My CV
    url: /myCV

email: youremail@test.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: peter3marsh
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: peterbmarsh
medium_username: 


# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: '' # the subpath of your site, e.g. /blog
url: "https://peterbmarsh.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version:
