name: Peter Marsh
title: "Hi, I'm Peter :) Welcome to my website"
description: "A UCLA Engineering Grad with a BS in Biomedical Engineering
and an emphasis in Computer Science. Click learn more about me!"
tags:
  - about me
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
